import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Bell, CalendarDays, CheckCircle2, ChevronDown, Clock3, Command, Inbox, LayoutDashboard, ListTodo, MessageSquare, Plus, Search, Users, X, Play, Pause, RotateCcw, CircleAlert} from 'lucide-react';
import {api} from './services/api';
import './styles.css';

const demoTasks=[
 {id:'demo-1',title:'Review supplier shipment documentation',description:'Confirm quantities, batch information and supporting documents before receiving the shipment.',status:'in_progress',priority:'high',due_at:'2026-09-29T15:30:00',source_type:'operational',entity_type:'purchase_order',entity_id:'PO-2048'},
 {id:'demo-2',title:'Follow up on finance approval',description:'Check the outstanding approval and update the requester.',status:'waiting',priority:'normal',due_at:'2026-09-29T16:00:00',source_type:'request'},
 {id:'demo-3',title:'Prepare tomorrow\'s work plan',description:'Review upcoming commitments and set priorities for tomorrow.',status:'inbox',priority:'normal',due_at:'2026-09-29T17:00:00',source_type:'manual'}
];

function App(){
 const [page,setPage]=useState('day'); const [tasks,setTasks]=useState([]); const [selected,setSelected]=useState(null); const [query,setQuery]=useState(''); const [timer,setTimer]=useState(false); const [elapsed,setElapsed]=useState(0); const [notifications,setNotifications]=useState(0); const [staff,setStaff]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{ loadWorkspace(); },[]);
 useEffect(()=>{ if(!timer)return; const i=setInterval(()=>setElapsed(v=>v+1),1000); return()=>clearInterval(i)},[timer]);
 async function loadWorkspace(){ try{setLoading(true); const data=await api.workspace(); setStaff(data.staff); setTasks(data.tasks||[]); setNotifications(data.summary?.unread_notifications||0); if(data.active_time){setTimer(data.active_time.status==='active'); setElapsed(data.active_time.total_seconds||0)} }catch(e){setError('Backend unavailable — showing local workspace preview.'); setTasks(demoTasks); setNotifications(3)}finally{setLoading(false)} }
 async function toggleWork(){ try{ if(timer){ await api.time.pause(); setTimer(false); } else { await api.time.start(); setTimer(true); } }catch(e){ setTimer(v=>!v); } }
 const filtered=useMemo(()=>tasks.filter(t=>(t.title+' '+(t.description||'')).toLowerCase().includes(query.toLowerCase())),[tasks,query]);
 const complete=async(id)=>{ try{const updated=await api.completeTask(id); setTasks(ts=>ts.map(t=>t.id===id?updated:{...t}));}catch(e){setTasks(ts=>ts.map(t=>t.id===id?{...t,status:'completed',completed_at:new Date().toISOString()}:t))} setSelected(null)};
 const addTask=async()=>{const body={title:'New task',description:'Add details and assign an owner.',priority:'normal',source_type:'manual'}; try{const created=await api.createTask(body); setTasks(ts=>[created,...ts]);}catch(e){setTasks(ts=>[{id:'demo-'+Date.now(),...body,status:'inbox'},...ts])}};
 return <div className="app">
   <header className="topbar"><div className="brand">Synbot <span>Staff Workspace</span></div><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your work..."/><kbd>⌘ K</kbd></div><button className={'timer '+(timer?'live':'')} onClick={toggleWork}>{timer?<Pause size={16}/>:<Play size={16}/>} {timer?'Working':'Start work'} <strong>{fmt(elapsed)}</strong></button><button className="iconbtn" onClick={()=>setNotifications(0)}><Bell size={18}/>{notifications>0&&<i>{notifications}</i>}</button><div className="avatar">{(staff?.name||'MA').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}</div></header>
   <aside className="sidebar"><div className="company">{staff?.company_name||'Atiat Limited'} <ChevronDown size={14}/></div><Nav icon={<LayoutDashboard/>} label="My Day" active={page==='day'} onClick={()=>setPage('day')}/><Nav icon={<ListTodo/>} label="My Work" active={page==='work'} onClick={()=>setPage('work')}/><Nav icon={<Inbox/>} label="Inbox" active={page==='inbox'} onClick={()=>setPage('inbox')} badge={notifications}/><Nav icon={<Users/>} label="Team" active={page==='team'} onClick={()=>setPage('team')}/><Nav icon={<CalendarDays/>} label="Progress" active={page==='progress'} onClick={()=>setPage('progress')}/><div className="sidebarBottom"><Nav icon={<Command/>} label="Command bar"/><Nav icon={<MessageSquare/>} label="Ask Synbot"/></div></aside>
   <main className="main">{error&&<div className="notice">{error}</div>}{loading&&<div className="loading">Loading your workspace…</div>}{page==='day'&&<MyDay tasks={filtered} onOpen={setSelected} onAdd={addTask}/>} {page==='work'&&<Work tasks={filtered} onOpen={setSelected}/>} {page==='inbox'&&<InboxPage tasks={filtered} onOpen={setSelected}/>} {page==='team'&&<Team/>} {page==='progress'&&<Progress tasks={tasks}/>}</main>
   {selected&&<TaskDrawer task={selected} onClose={()=>setSelected(null)} onComplete={complete}/>} 
 </div>
}
function Nav({icon,label,active,onClick,badge}){return <button className={'nav '+(active?'active':'')} onClick={onClick}>{React.cloneElement(icon,{size:18})}<span>{label}</span>{badge>0&&<b>{badge}</b>}</button>}
function MyDay({tasks,onOpen,onAdd}){const attention=tasks.filter(t=>t.status==='waiting'||t.priority==='high'); return <><div className="hero"><div><p className="eyebrow">Tuesday, 29 September</p><h1>Good afternoon, Mofe.</h1><p className="muted">Here’s what needs your attention today.</p></div><button className="primary" onClick={onAdd}><Plus size={17}/> Add task</button></div><div className="cards"><Metric label="My tasks" value={tasks.filter(t=>t.status!=='completed').length} icon={<ListTodo/>}/><Metric label="Due today" value={tasks.length} icon={<CalendarDays/>}/><Metric label="Waiting" value={tasks.filter(t=>t.status==='waiting').length} icon={<Clock3/>}/><Metric label="Work time" value="—" icon={<Clock3/>}/></div><div className="grid"><section className="panel"><div className="panelHead"><h2>Today</h2><span>{tasks.length} items</span></div>{tasks.slice(0,5).map(t=><TaskRow key={t.id} task={t} onClick={()=>onOpen(t)}/>)}</section><section className="panel"><div className="panelHead"><h2>Needs attention</h2><CircleAlert size={18}/></div>{attention.length?attention.map(t=><TaskRow compact key={t.id} task={t} onClick={()=>onOpen(t)} />):<Empty text="Nothing urgent right now."/>}</section></div><section className="panel activity"><div className="panelHead"><h2>Recent activity</h2></div><Activity text="Started work session" time="Just now"/><Activity text="Shipment documentation task moved to In progress" time="18 min ago"/><Activity text="Finance approval request is waiting" time="42 min ago"/></section></>}
function Work({tasks,onOpen}){return <><div className="pageHead"><div><p className="eyebrow">My work</p><h1>Your tasks</h1></div><button className="primary"><Plus size={17}/> Add task</button></div><div className="tabs"><span className="tab active">Today</span><span className="tab">Upcoming</span><span className="tab">Waiting</span><span className="tab">Completed</span></div><section className="panel">{tasks.map(t=><TaskRow key={t.id} task={t} onClick={()=>onOpen(t)}/>)}</section></>}
function InboxPage({tasks,onOpen}){return <><div className="pageHead"><div><p className="eyebrow">Inbox</p><h1>Things that need you</h1></div></div><section className="panel">{tasks.filter(t=>t.status!=='completed').map(t=><TaskRow key={t.id} task={t} onClick={()=>onOpen(t)}/>)}</section></>}
function Team(){return <><div className="pageHead"><div><p className="eyebrow">Team</p><h1>Who can help?</h1></div></div><div className="teamgrid">{['Adaeze Okafor','Daniel Mensah','Tomi Adebayo','Ibrahim Yusuf'].map((n,i)=><div className="member" key={n}><div className="avatar large">{n.split(' ').map(x=>x[0]).join('')}</div><div><strong>{n}</strong><p>{['Procurement','Finance','Operations','HR'][i]}</p></div><span className="online">Available</span><button className="ghost">Message</button></div>)}</div></>}
function Progress({tasks}){const completed=tasks.filter(t=>t.status==='completed').length;return <><div className="pageHead"><div><p className="eyebrow">Progress</p><h1>Your week</h1></div></div><div className="cards"><Metric label="Completed" value={completed} icon={<CheckCircle2/>}/><Metric label="Active" value={tasks.filter(t=>t.status==='in_progress').length} icon={<ListTodo/>}/><Metric label="Waiting" value={tasks.filter(t=>t.status==='waiting').length} icon={<Clock3/>}/><Metric label="Requests handled" value="—" icon={<MessageSquare/>}/></div><section className="panel journal"><div className="panelHead"><h2>Work journal</h2></div><Activity text="Task activity and operational events will appear here." time="This week"/></section></>}
function Metric({label,value,icon}){return <div className="metric"><div className="metricIcon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}
function TaskRow({task,onClick,compact}){return <button className={'task '+(compact?'compact':'')} onClick={onClick}><div className={'dot '+task.priority}></div><div className="taskMain"><strong>{task.title}</strong><p>{task.description}</p><div className="meta"><span>{label(task.status)}</span>{task.entity_type&&<span>{task.entity_type.replaceAll('_',' ')}</span>}{task.due_at&&<span>Due {new Date(task.due_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span>}</div></div><ChevronDown className="chev" size={17}/></button>}
function TaskDrawer({task,onClose,onComplete}){return <div className="overlay"><aside className="drawer"><div className="drawerHead"><span className="eyebrow">Task</span><button className="iconbtn" onClick={onClose}><X/></button></div><h2>{task.title}</h2><div className="badges"><span>{label(task.status)}</span><span>{task.priority}</span>{task.source_type&&<span>{task.source_type}</span>}</div><p className="drawerDesc">{task.description}</p>{task.entity_type&&<div className="reference"><small>Business reference</small><strong>{task.entity_type.replaceAll('_',' ')} · {task.entity_id}</strong></div>}<div className="checklist"><h3>Checklist</h3><label><input type="checkbox"/> Confirm details</label><label><input type="checkbox"/> Complete required action</label><label><input type="checkbox"/> Add supporting note</label></div><div className="comment"><MessageSquare size={17}/><input placeholder="Add a comment..."/></div><div className="drawerActions"><button className="ghost" onClick={onClose}>Close</button><button className="primary" onClick={()=>onComplete(task.id)}><CheckCircle2 size={17}/> Complete</button></div></aside></div>}
function Activity({text,time}){return <div className="activityRow"><div className="activityDot"></div><div><strong>{text}</strong><p>{time}</p></div></div>}
function Empty({text}){return <div className="empty">{text}</div>}
function label(s){return s?.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())||'Task'}
function fmt(sec){return `${String(Math.floor(sec/3600)).padStart(2,'0')}:${String(Math.floor(sec/60)%60).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
createRoot(document.getElementById('root')).render(<App/>);
