-- Migration 006: Create Inventory Events Table for Delta Tracking
-- This table tracks inventory movements that occur *after* the last Sage snapshot
-- ensuring strict separation between "System of Record" (Sage) and "System of Intelligence" (Synbot).

CREATE TABLE IF NOT EXISTS placeware_inventory_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT NOT NULL,
    quantity_change NUMERIC NOT NULL,
    event_type TEXT NOT NULL CHECK (event_type IN ('SALE', 'RESTOCK', 'DAMAGE', 'EXPIRY', 'ADJUSTMENT')),
    reference TEXT, -- Order number, delivery note, or reason
    performed_by TEXT, -- User ID or Name from JWT
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optimize for SKU lookups (critical for "Do we have X in stock?")
CREATE INDEX IF NOT EXISTS idx_inventory_events_sku ON placeware_inventory_events(sku);

-- Optimize for time-based queries (reconciliation)
CREATE INDEX IF NOT EXISTS idx_inventory_events_created_at ON placeware_inventory_events(created_at);
