-- Migration 007: Phase 2 - Staff & Operational Layer
-- Foundational registry for staff + timesheet tracking
-- NOTE: Intentionally lightweight, not a full HRIS/Payroll system

-- 1. Staff Registry
CREATE TABLE IF NOT EXISTS placeware_staff (
    staff_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    department TEXT NOT NULL CHECK (department IN ('Finance', 'Sales', 'Operations', 'HR', 'Management')),
    role TEXT, -- Free text (e.g., 'Warehouse Manager', 'Senior Accountant')
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optimize for department filtering & email lookups
CREATE INDEX IF NOT EXISTS idx_staff_department ON placeware_staff(department);
CREATE INDEX IF NOT EXISTS idx_staff_email ON placeware_staff(email);

-- 2. Timesheet Tracking
CREATE TABLE IF NOT EXISTS placeware_timesheets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id UUID REFERENCES placeware_staff(staff_id) ON DELETE CASCADE,
    date DATE NOT NULL,
    hours_worked NUMERIC(5, 2) NOT NULL CHECK (hours_worked > 0 AND hours_worked <= 24),
    department TEXT NOT NULL, -- Snapshot at time of entry (in case staff moves)
    activity_note TEXT,
    recorded_by TEXT, -- User ID (auditable actor)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optimize for operational queries ("Who worked today?", "Weekly hours")
CREATE INDEX IF NOT EXISTS idx_timesheets_date ON placeware_timesheets(date);
CREATE INDEX IF NOT EXISTS idx_timesheets_staff ON placeware_timesheets(staff_id);
