-- Migration 008: Phase 3 - Intelligence & Alerts
-- Support for dashboards, alerts, and executive briefings
-- Requires Phase 1 (Inventory) and Phase 2 (Staff)

-- 1. Alerting System (Notification Log)
CREATE TABLE IF NOT EXISTS placeware_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
    category TEXT NOT NULL CHECK (category IN ('finance', 'inventory', 'workforce', 'system')),
    status TEXT DEFAULT 'unread' CHECK (status IN ('unread', 'read', 'archived')),
    metadata JSONB, -- Context (e.g. { "sku": "A123", "threshold": 10 })
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optimize for dashboard feeds ("Show me active critical alerts")
CREATE INDEX IF NOT EXISTS idx_alerts_status_severity ON placeware_alerts(status, severity);
CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON placeware_alerts(created_at);

-- 2. Daily Briefing Cache (Optional but recommended for performance)
-- Stores the generated JSON summary to avoid re-calculating expensive aggregations repeatedly
CREATE TABLE IF NOT EXISTS placeware_executive_briefings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_date DATE UNIQUE DEFAULT CURRENT_DATE,
    content JSONB NOT NULL, -- The full structured briefing
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
