-- Migration 023: Create webhook idempotency table for high-volume checks

create table if not exists public.placeware_webhook_idempotency (
  id bigint generated by default as identity primary key,
  idempotency_key text not null,
  tracking_id uuid,
  provider text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create unique index if not exists uq_webhook_idempotency_key on public.placeware_webhook_idempotency(idempotency_key);
create index if not exists idx_webhook_idempotency_created on public.placeware_webhook_idempotency(created_at desc);

-- Optional retention policy note: consider periodic cleanup of old idempotency rows
