-- Migration 025: Create email events table for observability of background sends

create table if not exists public.placeware_email_events (
  id bigint generated by default as identity primary key,
  msg_subject text,
  recipient text,
  status text not null default 'queued' check (status in ('queued','sent','failed')),
  attempts int not null default 0,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz
);

create index if not exists idx_email_events_recipient on public.placeware_email_events(recipient);
create index if not exists idx_email_events_status on public.placeware_email_events(status);
