"""Sage 50 (2013) Import/Export column layouts -- GENERATED, do not hand-edit.

Source: backend/docs/Latestmods-TB/sage-link/export-templates/*.CSV, exported
from the client's own Sage via File > Select Import/Export > Export with all
fields shown. HEADERS are copied verbatim (order matters: Sage maps import
columns by position against the template). CONSTANTS are the columns whose
value never varied across every row of the sample export -- used as the
fill value for columns a builder does not set.
"""

HEADERS = {'sales': ['Customer ID',
           'Customer Name',
           'Invoice/CM #',
           'Apply to Invoice Number',
           'Credit Memo',
           'Progress Billing Invoice',
           'Date',
           'Ship By',
           'Quote',
           'Quote #',
           'Quote Good Thru Date',
           'Drop Ship',
           'Ship to Name',
           'Ship to Address-Line One',
           'Ship to Address-Line Two',
           'Ship to City',
           'Ship to State',
           'Ship to Zipcode',
           'Ship to Country',
           'Customer PO',
           'Ship Via',
           'Ship Date',
           'Date Due',
           'Discount Amount',
           'Discount Date',
           'Displayed Terms',
           'Sales Representative ID',
           'Accounts Receivable Account',
           'Accounts Receivable Amount',
           'Sales Tax ID',
           'Invoice Note',
           'Note Prints After Line Items',
           'Statement Note',
           'Stmt Note Prints Before Ref',
           'Internal Note',
           'Beginning Balance Transaction',
           'AR Date Cleared in Bank Rec',
           'Number of Distributions',
           'Invoice/CM Distribution',
           'Apply to Invoice Distribution',
           'Apply To Sales Order',
           'Apply to Proposal',
           'Quantity',
           'SO/Proposal Number',
           'Item ID',
           'Serial Number',
           'SO/Proposal Distribution',
           'Description',
           'G/L Account',
           'GL Date Cleared in Bank Rec',
           'Unit Price',
           'Tax Type',
           'UPC / SKU',
           'Weight',
           'Amount',
           'Inventory Account',
           'Inv Acnt Date Cleared In Bank Rec',
           'Cost of Sales Account',
           'COS Acnt Date Cleared In Bank Rec',
           'U/M ID',
           'U/M No. of Stocking Units',
           'Stocking Quantity',
           'Stocking Unit Price',
           'Cost of Sales Amount',
           'Job ID',
           'Sales Tax Agency ID',
           'Transaction Period',
           'Transaction Number',
           'Receipt Number',
           'Return Authorization',
           'Voided by Transaction',
           'Retainage Percent',
           'Recur Number',
           'Recur Frequency'],
 'receipts': ['Deposit Ticket ID',
              'Customer ID',
              'Customer Name',
              'Reference',
              'Date',
              'Payment Method',
              'Cash Account',
              'Cash Amount',
              'Sales Representative ID',
              'Sales Tax ID',
              'Total Paid on Invoice(s)',
              'Discount Account',
              'Prepayment',
              'Vendor Receipt',
              'AR Date Cleared in Bank Rec',
              'Number of Distributions',
              'Invoice Paid',
              'Discount Amount',
              'Disc Date Cleared In Bank Rec',
              'Quantity',
              'Stocking Quantity',
              'Item ID',
              'Serial Number',
              'U/M ID',
              'U/M No. of Stocking Units',
              'Description',
              'G/L Account',
              'GL Date Cleared in Bank Rec',
              'Unit Price',
              'Stocking Unit Price',
              'Tax Type',
              'UPC / SKU',
              'Weight',
              'Amount',
              'Inventory Account',
              'Inv Acnt Date Cleared In Bank Rec',
              'Cost of Sales Account',
              'COS Acnt Date Cleared In Bank Rec',
              'Cost of Sales Amount',
              'Job ID',
              'Sales Tax Agency ID',
              'Transaction Period',
              'Transaction Number',
              'Receipt Number',
              "Card/Check Holder's Name",
              'Card/Check Address Line 1',
              'Card/Check Address Line 2',
              'Card/Check City',
              'Card/Check State',
              'Card/Check Zip Code',
              'Card/Check Country',
              'Credit Card Stored Reference',
              'Merchant ID',
              'Last Known CC Number',
              'Last Known CC Expiration Date',
              'Card/Check Auth. Code',
              'Card/Check Authorized Status',
              'Credit Card Comment',
              'Authorized Amount'],
 'adjust': ['Item ID',
            'Reference',
            'Date',
            'Job ID',
            'Reason to Adjust',
            'Inventory Account',
            'Amount Adjusted',
            'Inv Acnt Date Cleared in Bank Rec',
            'Number of Distributions',
            'G/L Source Account',
            'GL Date Cleared in Bank Rec',
            'Unit Cost',
            'Quantity',
            'Amount',
            'Transaction Period',
            'Transaction Number',
            'Serial Number'],
 'customer': ['Customer ID',
              'Customer Name',
              'Prospect',
              'Inactive',
              'Bill to Contact First Name',
              'Bill to Contact Last Name',
              'Bill to Address-Line One',
              'Bill to Address-Line Two',
              'Bill to City',
              'Bill to State',
              'Bill to Zip',
              'Bill to Country',
              'Bill to Sales Tax ID',
              'Ship to Address 1-Line One',
              'Ship to Address 1-Line Two',
              'Ship to City 1',
              'Ship to State 1',
              'Ship to Zipcode 1',
              'Ship to Country 1',
              'Ship to Sales Tax ID 1',
              'Customer Type',
              'Telephone 1',
              'Telephone 2',
              'Fax Number',
              'Customer E-mail',
              'Sales Representative ID',
              'Account #',
              'G/L Sales Account',
              'Open Purchase Order Number',
              'Ship Via',
              'Resale Number',
              'Pricing Level',
              'Use Standard Terms',
              'C.O.D. Terms',
              'Prepaid Terms',
              'Terms Type',
              'Due Days',
              'Discount Days',
              'Discount Percent',
              'Credit Limit',
              'Credit Status',
              'Charge Finance Charges',
              'Due Month End Terms',
              "Cardholder's Name",
              'Credit Card Address Line 1',
              'Credit Card Address Line 2',
              'Credit Card City',
              'Credit Card State',
              'Credit Card Zip Code',
              'Credit Card Country',
              'Credit Card Stored Reference',
              'Merchant ID',
              'Last Known CC Number',
              'Last Known CC Expiration Date',
              'Use Receipt Settings',
              'Customer Payment Method',
              'Customer Cash Account',
              'Second Contact',
              'Reference',
              'Mailing List?',
              'Multiple Sites?',
              'Customer Since Date',
              'Last Statement Date',
              'Customer Web Site',
              'ID Replacement']}

CONSTANTS = {'sales': {'Progress Billing Invoice': 'FALSE',
           'Ship By': '',
           'Quote': 'FALSE',
           'Quote #': '',
           'Quote Good Thru Date': '',
           'Drop Ship': 'FALSE',
           'Ship to State': '',
           'Customer PO': '',
           'Ship Date': '',
           'Discount Amount': '0.00',
           'Sales Representative ID': '',
           'Accounts Receivable Account': '11000',
           'Sales Tax ID': '',
           'Note Prints After Line Items': 'FALSE',
           'Statement Note': '',
           'Stmt Note Prints Before Ref': 'FALSE',
           'Internal Note': '',
           'Beginning Balance Transaction': 'FALSE',
           'AR Date Cleared in Bank Rec': '',
           'Apply To Sales Order': 'FALSE',
           'Apply to Proposal': 'FALSE',
           'SO/Proposal Number': '',
           'Serial Number': '',
           'SO/Proposal Distribution': '0',
           'GL Date Cleared in Bank Rec': '',
           'Tax Type': '1',
           'Weight': '0.00',
           'Inv Acnt Date Cleared In Bank Rec': '',
           'COS Acnt Date Cleared In Bank Rec': '',
           'U/M No. of Stocking Units': '1.00',
           'Job ID': '',
           'Sales Tax Agency ID': '',
           'Transaction Period': '34',
           'Receipt Number': '',
           'Return Authorization': '',
           'Voided by Transaction': '',
           'Retainage Percent': '0.00',
           'Recur Number': '0',
           'Recur Frequency': '0'},
 'receipts': {'Deposit Ticket ID': '',
              'Sales Representative ID': '',
              'Sales Tax ID': '',
              'Discount Account': '',
              'Vendor Receipt': 'FALSE',
              'AR Date Cleared in Bank Rec': '',
              'Discount Amount': '0.00',
              'Disc Date Cleared In Bank Rec': '',
              'Quantity': '0.00',
              'Stocking Quantity': '0.00',
              'Item ID': '',
              'Serial Number': '',
              'U/M ID': '',
              'G/L Account': '11000',
              'GL Date Cleared in Bank Rec': '',
              'Unit Price': '0.00',
              'Stocking Unit Price': '0.00',
              'UPC / SKU': '',
              'Weight': '0.00',
              'Inventory Account': '',
              'Inv Acnt Date Cleared In Bank Rec': '',
              'Cost of Sales Account': '',
              'COS Acnt Date Cleared In Bank Rec': '',
              'Cost of Sales Amount': '0.00',
              'Job ID': '',
              'Sales Tax Agency ID': '',
              'Transaction Period': '34',
              "Card/Check Holder's Name": '',
              'Card/Check Address Line 1': '',
              'Card/Check Address Line 2': '',
              'Card/Check City': '',
              'Card/Check State': '',
              'Card/Check Zip Code': '',
              'Card/Check Country': '',
              'Credit Card Stored Reference': '{00000000-0000-0000-0000-000000000000}',
              'Merchant ID': '',
              'Last Known CC Number': '',
              'Last Known CC Expiration Date': '',
              'Card/Check Auth. Code': '',
              'Card/Check Authorized Status': '0',
              'Credit Card Comment': '',
              'Authorized Amount': '0.00'},
 'adjust': {},
 'customer': {'Inactive': 'FALSE',
              'Bill to State': '',
              'Bill to Sales Tax ID': '',
              'Ship to City 1': '',
              'Ship to State 1': '',
              'Ship to Zipcode 1': '',
              'Ship to Country 1': '',
              'Ship to Sales Tax ID 1': '',
              'Customer Type': '',
              'Fax Number': '',
              'Sales Representative ID': '',
              'Open Purchase Order Number': '',
              'Resale Number': '',
              'Pricing Level': '0',
              'Prepaid Terms': 'FALSE',
              'Terms Type': 'FALSE',
              'Due Days': '30',
              'Discount Days': '0',
              'Discount Percent': '0.00000',
              'Credit Status': '1',
              'Charge Finance Charges': 'FALSE',
              'Due Month End Terms': 'FALSE',
              "Cardholder's Name": '',
              'Credit Card State': '',
              'Credit Card Zip Code': '',
              'Credit Card Country': '',
              'Credit Card Stored Reference': '{00000000-0000-0000-0000-000000000000}',
              'Merchant ID': '',
              'Last Known CC Number': '',
              'Last Known CC Expiration Date': '',
              'Use Receipt Settings': 'TRUE',
              'Customer Payment Method': '',
              'Customer Cash Account': '',
              'Reference': '',
              'Mailing List?': '',
              'Multiple Sites?': '',
              'Last Statement Date': '',
              'Customer Web Site': '',
              'ID Replacement': '0'}}
